#!/usr/bin/env python3
"""Download ElevenLabs preview audio from a voices CSV and build metadata mapping."""

from __future__ import annotations

import argparse
import csv
import json
import sys
import time
from pathlib import Path
from typing import Dict, List

import requests


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Download preview audio and map audio files with descriptions"
    )
    parser.add_argument(
        "--input-csv",
        default="tools/elevenlabs_voices_vi.csv",
        help="Input CSV generated by crawl_elevenlabs_voices.py",
    )
    parser.add_argument(
        "--output-dir",
        default="tools/elevenlabs_previews_vi",
        help="Directory to store downloaded preview audio",
    )
    parser.add_argument(
        "--metadata-csv",
        default="tools/elevenlabs_previews_vi/metadata.csv",
        help="Output metadata CSV (audio path + description mapping)",
    )
    parser.add_argument(
        "--metadata-jsonl",
        default="tools/elevenlabs_previews_vi/metadata.jsonl",
        help="Output metadata JSONL (audio path + description mapping)",
    )
    parser.add_argument("--timeout", type=int, default=30, help="HTTP timeout seconds")
    parser.add_argument("--sleep", type=float, default=0.1, help="Delay between downloads")
    parser.add_argument(
        "--skip-existing",
        action="store_true",
        help="Skip files that already exist",
    )
    return parser.parse_args()


def load_rows(path: Path) -> List[Dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def build_filename(voice_id: str, preview_url: str) -> str:
    ext = Path(preview_url.split("?")[0]).suffix.lower() or ".mp3"
    return f"{voice_id}{ext}"


def download_file(
    session: requests.Session,
    url: str,
    output_path: Path,
    timeout: int,
) -> None:
    with session.get(url, stream=True, timeout=timeout) as resp:
        resp.raise_for_status()
        with output_path.open("wb") as f:
            for chunk in resp.iter_content(chunk_size=1024 * 64):
                if chunk:
                    f.write(chunk)


def save_metadata_csv(path: Path, rows: List[Dict[str, str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    columns = [
        "voice_id",
        "name",
        "description",
        "audio_path",
        "preview_url",
        "language",
        "locale",
        "gender",
        "age",
        "accent",
        "category",
        "descriptive",
        "use_case",
    ]
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=columns)
        writer.writeheader()
        writer.writerows(rows)


def save_metadata_jsonl(path: Path, rows: List[Dict[str, str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")


def main() -> int:
    args = parse_args()
    input_csv = Path(args.input_csv)
    output_dir = Path(args.output_dir)

    if not input_csv.exists():
        print(f"Input CSV not found: {input_csv}", file=sys.stderr)
        return 1

    output_dir.mkdir(parents=True, exist_ok=True)
    raw_rows = load_rows(input_csv)

    session = requests.Session()
    session.headers.update(
        {
            "User-Agent": (
                "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
                "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
            )
        }
    )

    mapped_rows: List[Dict[str, str]] = []
    ok = 0
    skipped = 0
    failed = 0

    for idx, row in enumerate(raw_rows, start=1):
        voice_id = (row.get("voice_id") or "").strip()
        preview_url = (row.get("preview_url") or "").strip()

        if not voice_id or not preview_url:
            failed += 1
            print(f"[{idx}] skip invalid row: voice_id/preview_url missing")
            continue

        filename = build_filename(voice_id, preview_url)
        audio_path = output_dir / filename

        if args.skip_existing and audio_path.exists():
            skipped += 1
        else:
            try:
                download_file(
                    session=session,
                    url=preview_url,
                    output_path=audio_path,
                    timeout=args.timeout,
                )
                ok += 1
                time.sleep(args.sleep)
            except Exception as exc:
                failed += 1
                print(f"[{idx}] failed voice_id={voice_id}: {exc}", file=sys.stderr)
                continue

        mapped_rows.append(
            {
                "voice_id": voice_id,
                "name": row.get("name", ""),
                "description": row.get("description", ""),
                "audio_path": str(audio_path),
                "preview_url": preview_url,
                "language": row.get("language", ""),
                "locale": row.get("locale", ""),
                "gender": row.get("gender", ""),
                "age": row.get("age", ""),
                "accent": row.get("accent", ""),
                "category": row.get("category", ""),
                "descriptive": row.get("descriptive", ""),
                "use_case": row.get("use_case", ""),
            }
        )

        print(f"[{idx}] ok voice_id={voice_id} -> {audio_path.name}")

    save_metadata_csv(Path(args.metadata_csv), mapped_rows)
    save_metadata_jsonl(Path(args.metadata_jsonl), mapped_rows)

    print(f"Downloaded: {ok}, skipped: {skipped}, failed: {failed}")
    print(f"Metadata CSV : {args.metadata_csv}")
    print(f"Metadata JSONL: {args.metadata_jsonl}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
